spring.application.name=RetourMarche

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.database-platform=${SPRING_JPA_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
server.forward-headers-strategy=native

# Observability
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# Resilience4j Configuration
resilience4j.circuitbreaker.instances.mainService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.mainService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.mainService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.mainService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.mainService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.mainService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.mainService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.mainService.eventConsumerBufferSize=10

resilience4j.bulkhead.instances.mainService.maxConcurrentCalls=10
resilience4j.bulkhead.instances.mainService.maxWaitDuration=10ms


